import { StyleSheet } from "react-native";

export const FilterModalStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modal: {
    backgroundColor: "#283747",
    borderTopStartRadius: 30,
    borderTopEndRadius: 30,
    padding: 35,
    alignItems: "center",
    width: "100%",
    height: "75%",
  },
  button: {
    backgroundColor: "#E74C3C",
    borderRadius: 5,
    padding: 10,
    paddingHorizontal: 15,
    elevation: 2,
    marginTop: 20,
  },
  headerText: {
    fontSize: 30,
    marginBottom: 20,
  },
  text: {
    textAlign: "center",
    fontFamily: "space-mono",
    fontSize: 15,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  search: {
    height: 50,
    width: "100%",
    backgroundColor: "#34495E",
    borderRadius: 12,
    paddingLeft: 10,
    color: "white",
  },
  sort: {
    width: "100%",
    height: 50,
    borderRadius: 12,
    backgroundColor: "#58D68D",
    borderColor: "#28B463",
    borderWidth: 2,
    paddingHorizontal: 10,
    margin: 10,
    justifyContent: "center",
  },
  filter: {
    backgroundColor: "#5DADE2",
    borderColor: "#2E86C1",
  },
  reset: {
    alignItems: "center",
    backgroundColor: "rgba(229, 231, 233, .3)",
    padding: 10,
    borderRadius: 10,
    paddingHorizontal: 20,
  },
  done: {
    alignItems: "center",
    backgroundColor: "rgba(255, 24, 178, .3)",
    padding: 10,
    borderRadius: 10,
    paddingHorizontal: 20,
  },
  bottomButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    alignItems: "center",
    margin: 10,
  },
  labelText: {
    textAlign: "left",
    fontSize: 18,
    fontFamily: "space-mono",
  },
  filtersWrapper: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  filtersHomeWrapper: {
    justifyContent: "space-between",
  },
  textInputWrapper: {
    width: "100%",
  },
  starRatingsWrapper: {
    paddingBottom: 20,
    height: "40%",
    backgroundColor: "#2E86C1",
  },
  starRowWrapper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
  },
  backButton: {
    borderRadius: 30,
    backgroundColor: "#2874A6",
    padding: 15,
    margin: 15,
  },
  watchedButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
    margin: 5,
    backgroundColor: "#212F3C",
    borderRadius: 30,
    borderColor: "#E5E7E9",
    borderWidth: 1,
  },
  watchedText: {
    fontSize: 15,
    textAlign: "left",
  },
  watchedRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  watchedContainer: {
    paddingBottom: 20,
    height: "40%",
    backgroundColor: "#2E86C1",
  },
  sorterContainer: {
    paddingBottom: 20,
    height: "90%",
  },
  sortSwitchWrapper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  sortScrollView: {
    flex: 1,
    width: "100%",
  },
  sortItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 5,
    margin: 10,
  },
  sortItemText: {
    fontSize: 15,
    textAlign: "left",
  },
  mediaTagsContainer: {
    paddingBottom: 20,
    height: "40%",
    paddingHorizontal: 0,
    backgroundColor: "#2E86C1",
  },
});
